--- # Initialize worker nodes

- hosts: managers
  remote_user: kube
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes

  tasks:
    - name: Get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: Set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- hosts: nodes
  remote_user: kube
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes

  tasks:
    - name: Remove debug file
      file:
        path: $HOME/joined.txt
        state: absent

    - name: Join cluster
      shell: "{{ hostvars['manager'].join_command }} >> joined.txt"
      args:
        chdir: $HOME
        creates: joined.txt
      register: node
